# Generated by Django 2.1 on 2018-12-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20181223_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberinfo',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
